general:
steps:
  mtaBuild:
    buildTarget: 'CF'

  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'i317632trial'
      space: 'Dev'
      credentialsId: 'CF_CREDENTIALSID'
